name: Deploy

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code for the deployment
      uses: actions/checkout@v2

    - name: SSH into the AWS instance machine and deploy the code there
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > key_file.pem
        chmod 400 key_file.pem
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no -t -i key_file.pem ubuntu@ec2-16-171-197-18.eu-north-1.compute.amazonaws.com "bash ./deploy.sh"